In [1]:
#1 ek data set banao jissme hours aur marks collumn ho 

import pandas as pd 
data={
    'Hours':[1,2,3,4,5,6,7,8,9,10],
    'Marks':[20,25,35,40,50,55,65,70,80,90]
}

df=pd.DataFrame(data)
df

   Hours  Marks
0      1     20
1      2     25
2      3     35
3      4     40
4      5     50
5      6     55
6      7     65
7      8     70
8      9     80
9     10     90

In [2]:
# 2. first 5 row dikhao 

df.head()

   Hours  Marks
0      1     20
1      2     25
2      3     35
3      4     40
4      5     50

In [3]:
# hours ko X aur marks ko  mein store karo 

x=['Hour']
y=['Marks']