In [50]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [20, 21, np.nan, 23, 24, 21, np.nan, 25],
    "Salary": [25000, 30000, np.nan, 35000, 40000, 30000, np.nan, 45000],
    "Experience": [1, 2, 1, np.nan, 4, 2, np.nan, 5],
    "City": ["Lucknow", "Delhi", "Lucknow", np.nan, "Delhi", "Delhi", "Lucknow", "Mumbai"],
    "Gender": ["Male", "Female", "Male", "Female", np.nan, "Female", "Male", "Female"],
    "Purchased": ["No", "Yes", "No", "Yes", "Yes", "No", "Yes", "Yes"]
})
print(df)

    Age   Salary  Experience     City  Gender Purchased
0  20.0  25000.0         1.0  Lucknow    Male        No
1  21.0  30000.0         2.0    Delhi  Female       Yes
2   NaN      NaN         1.0  Lucknow    Male        No
3  23.0  35000.0         NaN      NaN  Female       Yes
4  24.0  40000.0         4.0    Delhi     NaN       Yes
5  21.0  30000.0         2.0    Delhi  Female        No
6   NaN      NaN         NaN  Lucknow    Male       Yes
7  25.0  45000.0         5.0   Mumbai  Female       Yes

## 🟢 Level 1 — Missing Values

Q1-Check karo ki har column mein kitne missing values hain.

In [51]:
print(df.isnull().sum())

Age           2
Salary        2
Experience    2
City          1
Gender        1
Purchased     0
dtype: int64

Q2.Age ke missing values ko mean se fill karo.

In [52]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [53]:
# Q3-Salary ke missing values ko median se fill karo.

df["Salary"] = df["Salary"].fillna(df["Salary"].median())

df

         Age   Salary  Experience     City  Gender Purchased
0  20.000000  25000.0         1.0  Lucknow    Male        No
1  21.000000  30000.0         2.0    Delhi  Female       Yes
2  22.333333  32500.0         1.0  Lucknow    Male        No
3  23.000000  35000.0         NaN      NaN  Female       Yes
4  24.000000  40000.0         4.0    Delhi     NaN       Yes
5  21.000000  30000.0         2.0    Delhi  Female        No
6  22.333333  32500.0         NaN  Lucknow    Male       Yes
7  25.000000  45000.0         5.0   Mumbai  Female       Yes

In [54]:
# 4.Experience ke missing values ko mean se fill karo 

df["Experience"] = df["Experience"].fillna(df["Experience"]
                                           .mean()
)

In [55]:
# 5.City ke missing values ko mode se fill karo.

df["City"]=df["City"].fillna(df["City"].mode())
df["City"]

0    Lucknow
1      Delhi
2    Lucknow
3        NaN
4      Delhi
5      Delhi
6    Lucknow
7     Mumbai
Name: City, dtype: object

In [56]:
#  6 Gender ke missing values ko mode se fill karo.

df["Gender"]=df["Gender"].fillna(df["Gender"].mode()[0])
df["Gender"]

0      Male
1    Female
2      Male
3    Female
4    Female
5    Female
6      Male
7    Female
Name: Gender, dtype: object

In [57]:
# 7-Confirm karo ki ab DataFrame mein koi missing value nahi hai.

df.isnull().sum()

Age           0
Salary        0
Experience    0
City          1
Gender        0
Purchased     0
dtype: int64

## 🟡 Level 2 — Encoding

In [58]:
df

         Age   Salary  Experience     City  Gender Purchased
0  20.000000  25000.0         1.0  Lucknow    Male        No
1  21.000000  30000.0         2.0    Delhi  Female       Yes
2  22.333333  32500.0         1.0  Lucknow    Male        No
3  23.000000  35000.0         2.5      NaN  Female       Yes
4  24.000000  40000.0         4.0    Delhi  Female       Yes
5  21.000000  30000.0         2.0    Delhi  Female        No
6  22.333333  32500.0         2.5  Lucknow    Male       Yes
7  25.000000  45000.0         5.0   Mumbai  Female       Yes

In [60]:
# 8-Gender ko numerical form mein convert karo:

df["Gender"]=df["Gender"].map({"NO":0,"Yes":1})
df["Gender"]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
Name: Gender, dtype: float64