In [134]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


df = pd.DataFrame({
    "Age": [20, 21, np.nan, 23, 24, 21, np.nan, 25],
    "Salary": [25000, 30000, np.nan, 35000, 40000, 30000, np.nan, 45000],
    "Experience": [1, 2, 1, np.nan, 4, 2, np.nan, 5],
    "City": ["Lucknow", "Delhi", "Lucknow", np.nan, "Delhi", "Delhi", "Lucknow", "Mumbai"],
    "Gender": ["Male", "Female", "Male", "Female", np.nan, "Female", "Male", "Female"],
    "Purchased": ["No", "Yes", "No", "Yes", "Yes", "No", "Yes", "Yes"]
})
print(df)

    Age   Salary  Experience     City  Gender Purchased
0  20.0  25000.0         1.0  Lucknow    Male        No
1  21.0  30000.0         2.0    Delhi  Female       Yes
2   NaN      NaN         1.0  Lucknow    Male        No
3  23.0  35000.0         NaN      NaN  Female       Yes
4  24.0  40000.0         4.0    Delhi     NaN       Yes
5  21.0  30000.0         2.0    Delhi  Female        No
6   NaN      NaN         NaN  Lucknow    Male       Yes
7  25.0  45000.0         5.0   Mumbai  Female       Yes

## 🟢 Level 1 — Missing Values

Q1-Check karo ki har column mein kitne missing values hain.

In [135]:
print(df.isnull().sum())

Age           2
Salary        2
Experience    2
City          1
Gender        1
Purchased     0
dtype: int64

Q2.Age ke missing values ko mean se fill karo.

In [136]:

df["Age"] = df["Age"].fillna(df["Age"].mean())

In [137]:
# Q3-Salary ke missing values ko median se fill karo.

df["Salary"] = df["Salary"].fillna(df["Salary"].median())

df

         Age   Salary  Experience     City  Gender Purchased
0  20.000000  25000.0         1.0  Lucknow    Male        No
1  21.000000  30000.0         2.0    Delhi  Female       Yes
2  22.333333  32500.0         1.0  Lucknow    Male        No
3  23.000000  35000.0         NaN      NaN  Female       Yes
4  24.000000  40000.0         4.0    Delhi     NaN       Yes
5  21.000000  30000.0         2.0    Delhi  Female        No
6  22.333333  32500.0         NaN  Lucknow    Male       Yes
7  25.000000  45000.0         5.0   Mumbai  Female       Yes

In [138]:
# 4.Experience ke missing values ko mean se fill karo 

df["Experience"] = df["Experience"].fillna(df["Experience"]
                                           .mean()
)

In [139]:
# 5.City ke missing values ko mode se fill karo.

df["City"]=df["City"].fillna(df["City"].mode())
df["City"]

0    Lucknow
1      Delhi
2    Lucknow
3        NaN
4      Delhi
5      Delhi
6    Lucknow
7     Mumbai
Name: City, dtype: object

In [140]:
#  6 Gender ke missing values ko mode se fill karo.

df["Gender"]=df["Gender"].fillna(df["Gender"].mode()[0])
df["Gender"]

0      Male
1    Female
2      Male
3    Female
4    Female
5    Female
6      Male
7    Female
Name: Gender, dtype: object

In [141]:
# 7-Confirm karo ki ab DataFrame mein koi missing value nahi hai.

df.isnull().sum()

Age           0
Salary        0
Experience    0
City          1
Gender        0
Purchased     0
dtype: int64

## 🟡 Level 2 — Encoding

In [142]:
df

         Age   Salary  Experience     City  Gender Purchased
0  20.000000  25000.0         1.0  Lucknow    Male        No
1  21.000000  30000.0         2.0    Delhi  Female       Yes
2  22.333333  32500.0         1.0  Lucknow    Male        No
3  23.000000  35000.0         2.5      NaN  Female       Yes
4  24.000000  40000.0         4.0    Delhi  Female       Yes
5  21.000000  30000.0         2.0    Delhi  Female        No
6  22.333333  32500.0         2.5  Lucknow    Male       Yes
7  25.000000  45000.0         5.0   Mumbai  Female       Yes

In [143]:
# 8-Gender ko numerical form mein convert karo:
df["Gender"]=df["Gender"].map({"NO":0,"Yes":1})
df["Gender"]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
Name: Gender, dtype: float64

In [144]:
# 9-Purchased ko numerical form mein convert karo:

df["Purchased"]=df["Purchased"].map({"No":0,"Yes":1})
df["Purchased"]

0    0
1    1
2    0
3    1
4    1
5    0
6    1
7    1
Name: Purchased, dtype: int64

In [145]:
# 10-City par One-Hot Encoding apply karo.

df=pd.get_dummies(df,columns=["City"],dtype=int)

df

,Age,Salary,Experience,Gender,Purchased,City_Delhi,City_Lucknow,City_Mumbai
0,20.000000,25000.0,1.0,NaN,0,0,1,0
1,21.000000,30000.0,2.0,NaN,1,1,0,0
2,22.333333,32500.0,1.0,NaN,0,0,1,0
3,23.000000,35000.0,2.5,NaN,1,0,0,0
4,24.000000,40000.0,4.0,NaN,1,1,0,0
5,21.000000,30000.0,2.0,NaN,0,1,0,0
6,22.333333,32500.0,2.5,NaN,1,0,1,0
7,25.000000,45000.0,5.0,NaN,1,0,0,1

## 🟠 Level 3 — Train/Test Split

In [146]:
# Q11.Purchased ko target y banao aur baaki columns ko features X banao.

X = df.drop("Purchased", axis=1)

y = df["Purchased"]

In [147]:
# Q12. Data ko 80%- traning ,20%- testing mein devide kro 

X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,
                                                random_state=42)
print("X_train:")
print(X_train)

print("X_test:")
print(X_test)

print("y_train:")
print(y_train)

print("y_test:")
print(y_test)

X_train:
         Age   Salary  Experience  Gender  City_Delhi  City_Lucknow  \
0  20.000000  25000.0         1.0     NaN           0             1
7  25.000000  45000.0         5.0     NaN           0             0
2  22.333333  32500.0         1.0     NaN           0             1
4  24.000000  40000.0         4.0     NaN           1             0
3  23.000000  35000.0         2.5     NaN           0             0
6  22.333333  32500.0         2.5     NaN           0             1

   City_Mumbai
0            0
7            1
2            0
4            0
3            0
6            0
X_test:
    Age   Salary  Experience  Gender  City_Delhi  City_Lucknow  City_Mumbai
1  21.0  30000.0         2.0     NaN           1             0            0
5  21.0  30000.0         2.0     NaN           1             0            0
y_train:
0    0
7    1
2    0
4    1
3    1
6    1
Name: Purchased, dtype: int64
y_test:
1    1
5    0
Name: Purchased, dtype: int64

## 🔵 Level 4 — Standardization

In [148]:
# Q13.Age, Salary, aur Experience ko standardize karo using:
scaler = StandardScaler()

X_train[["Age", "Salary", "Experience"]] = scaler.fit_transform(
    X_train[["Age", "Salary", "Experience"]]
)

In [149]:
#Q14Check karo scaling ke baad Age, Salary, 
# Experience ki values kaise change hui hain

X_test[["Age","Salary","Experience"]]=scaler.transform(
    X_test[["Age","Salary","Experience"]]
)

print(X_train)
print(X_test)

        Age    Salary  Experience  Gender  City_Delhi  City_Lucknow  \
0 -1.781176 -1.589439   -1.139606     NaN           0             1
7  1.424941  1.589439    1.595448     NaN           0             0
2 -0.284988 -0.397360   -1.139606     NaN           0             1
4  0.783718  0.794719    0.911685     NaN           1             0
3  0.142494  0.000000   -0.113961     NaN           0             0
6 -0.284988 -0.397360   -0.113961     NaN           0             1

   City_Mumbai
0            0
7            1
2            0
4            0
3            0
6            0
        Age    Salary  Experience  Gender  City_Delhi  City_Lucknow  \
1 -1.139953 -0.794719   -0.455842     NaN           1             0
5 -1.139953 -0.794719   -0.455842     NaN           1             0

   City_Mumbai
1            0
5            0

### 🔴 Level 5 — Complete Preprocessing

In [150]:
# 15.Starting dataset se lekar final ML-ready
#  data tak complete pipeline banao

print("Final X_train:")
print(X_train)

print("\ Final X_test:")
print(X_test)

print("\ final y_train:")
print(y_train)

print("\n Final y_test:")
print(y_test)

Final X_train:
        Age    Salary  Experience  Gender  City_Delhi  City_Lucknow  \
0 -1.781176 -1.589439   -1.139606     NaN           0             1
7  1.424941  1.589439    1.595448     NaN           0             0
2 -0.284988 -0.397360   -1.139606     NaN           0             1
4  0.783718  0.794719    0.911685     NaN           1             0
3  0.142494  0.000000   -0.113961     NaN           0             0
6 -0.284988 -0.397360   -0.113961     NaN           0             1

   City_Mumbai
0            0
7            1
2            0
4            0
3            0
6            0
\ Final X_test:
        Age    Salary  Experience  Gender  City_Delhi  City_Lucknow  \
1 -1.139953 -0.794719   -0.455842     NaN           1             0
5 -1.139953 -0.794719   -0.455842     NaN           1             0

   City_Mumbai
1            0
5            0
\ final y_train:
0    0
7    1
2    0
4    1
3    1
6    1
Name: Purchased, dtype: int64

 Final y_test:
1    1
5    0
Name: Purchased, dtype: int64

## 🟢 Phase 3 — Set 2: Encoding + Scaling Practice